README.md: guessinggame.sh
	echo "# Guessing Game\n" > README.md
	echo "Generated by \`make\` at **$$(date)**\n" >> README.md
	echo "The number of lines of code contained in \`guessinggame.sh\`: **$$(cat guessinggame.sh | wc -l | xargs expr)**" >> README.md

guessinggame.sh:
	touch guessinggame.sh